language: node_js
node_js:
  - "5"
  - "4"
addons:
  apt:
    packages:
      - xvfb
install:
  - npm install -g electron-prebuilt
  - npm install -g electron-mocha
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
notifications:
  email:
    on_success: never
    on_failure: change
